# Custom Enforced Rubocop Styles

LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
SignalException:
  Enabled: false
RaiseArgs:
  Enabled: false
ParameterLists:
  Enabled: false
AbcSize:
  Enabled: false
RedundantBegin:
  Enabled: false
PerceivedComplexity:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
RescueException:
  Enabled: false
NestedParenthesizedCalls:
  Enabled: false

# Custom Enforced Hound Ruby Styles

CollectionMethods:
  PreferredMethods:
    detect: find
StringLiterals:
  EnforcedStyle: single_quotes
SignalException:
  EnforcedStyle: only_raise
Style/FrozenStringLiteralComment:
  Enabled: false
# No extra empty lines.
Style/EmptyLines:
  Enabled: true
